language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
env:
    - DJANGO=3.0.7
    - DJANGO=3.1
    - DJANGO=3.2

install:

    - pip install -q Django==$DJANGO --use-mirrors
    - pip install pep8
    - pip install flake8
    - pip install -q -e . --use-mirrors
    - - pip install -r requirements.txt
before_script:
    - "pep8 --exclude=migrations --ignore=E501,E225 src"
    - pyflakes -x W src
script:
    - python manage.py test bus_stops.tests